#!/usr/bin/env node
// Converts the YAML result schema to JSON, and precompiles its Ajv
// validators to standalone JS, at build/test/dev time (04-throughput-
// measurement.md, 4.3b). The YAML file stays the source of truth; both
// outputs are generated and gitignored.
//
// Standalone compilation matters beyond speed: Ajv's normal `compile()`
// path builds each validator with `new Function(...)`, which Cloudflare
// Workers' runtime (and any CSP-restricted browser) refuses to run
// ("Code generation from strings disallowed"). `ajv/dist/standalone`
// emits plain JS instead, so no dynamic code generation happens at
// request time in either environment.

import { readFileSync, writeFileSync, mkdirSync } from "node:fs";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";
import { load } from "js-yaml";
import Ajv2020 from "ajv/dist/2020.js";
import addFormats from "ajv-formats";
import standaloneCode from "ajv/dist/standalone/index.js";

const root = dirname(dirname(fileURLToPath(import.meta.url)));
const SCHEMA_BASENAME = "p2p-speedtest-result.v1.schema";
const src = join(root, "schemas", `${SCHEMA_BASENAME}.yaml`);
const outDir = join(root, "app", "lib", "generated");
// Same basename as the source YAML, just re-extensioned — so a future v2
// schema's generated JSON/validators sit alongside this one under their
// own name instead of both fighting over one generic "result-schema.*".
const jsonOut = join(outDir, `${SCHEMA_BASENAME}.json`);
// ".js", not ".mjs": TS's bundler resolution pairs "foo.js" with a
// co-located "foo.d.ts" automatically; "foo.mjs" would need "foo.d.mts"
// instead. The package is "type": "module", so ".js" is still ESM.
const validatorsOut = join(outDir, `${SCHEMA_BASENAME}.validators.js`);
const validatorsDtsOut = join(outDir, `${SCHEMA_BASENAME}.validators.d.ts`);

const schema = load(readFileSync(src, "utf8"));
mkdirSync(outDir, { recursive: true });
writeFileSync(jsonOut, `${JSON.stringify(schema, null, 2)}\n`);
console.log(`Generated ${jsonOut}`);

// `code.source: true` retains what `standaloneCode` needs to extract;
// `strictTypes` is off because the schema's `if`/`then` conditional
// overrides nested `properties` without redeclaring an inherited `type` —
// valid, unambiguous JSON Schema that Ajv's strict linter otherwise flags.
const ajv = new Ajv2020.default({
  allErrors: true,
  strict: true,
  strictTypes: false,
  code: { source: true, esm: true },
});
addFormats.default(ajv);
ajv.addSchema(schema, schema.$id);
ajv.getSchema(`${schema.$id}#/$defs/data`);
ajv.getSchema(schema.$id);

let code = standaloneCode.default(ajv, {
  validateData: `${schema.$id}#/$defs/data`,
  validateEnvelope: schema.$id,
});

// The only escape hatch standalone codegen leaves for a format whose
// validator is a real function rather than an inlinable regex/literal
// (here, `date-time`): a runtime `require(...)`. Rewritten to a static
// import so Vite's bundler resolves it at build time instead of Workers
// ever seeing a `require` call.
const FORMATS_REQUIRE = /require\("ajv-formats\/dist\/formats"\)\.fullFormats/g;
if (FORMATS_REQUIRE.test(code)) {
  code = code.replace(FORMATS_REQUIRE, "__ajvFullFormats");
  code = `import { fullFormats as __ajvFullFormats } from "ajv-formats/dist/formats";\n${code}`;
}
if (code.includes("require(")) {
  throw new Error(
    "build-schema: standalone validator code still contains a require() call " +
      "the generator doesn't know how to rewrite — inspect the output before shipping it.",
  );
}
// The project's tsconfig turns on `checkJs`, which would otherwise
// typecheck Ajv's generated internals (and fail — they're written against
// looser shapes than strict mode allows). The hand-written `.d.ts` below
// is what consumers actually see; this file's own content is exempted.
code = `// @ts-nocheck\n${code}`;
writeFileSync(validatorsOut, code);
console.log(`Generated ${validatorsOut}`);

const dts = `// Generated by scripts/build-schema.mjs — do not edit.
export interface AjvValidateFn {
  (data: unknown): boolean;
  errors?: Array<{ instancePath: string; message?: string }> | null;
}
export declare const validateData: AjvValidateFn;
export declare const validateEnvelope: AjvValidateFn;
`;
writeFileSync(validatorsDtsOut, dts);
console.log(`Generated ${validatorsDtsOut}`);
